### ISSUE TITLE
First Steps: Could not locate node definition

### ISSUE THREAD

**Issue by stuartsierra** [pallet/pallet.github.com#16]
Hi, we're having trouble with the "First Steps" instructions at http://palletops.com/doc/first-steps/

Here is an example shell session with the final error message:

```
$ lein upgrade

$ lein version
Leiningen 1.7.1 on Java 1.6.0_29 Java HotSpot(TM) 64-Bit Server VM

$ lein plugin install lein-newnew 0.2.4

$ lein plugin install org.cloudhoist/lein-pallet-new 0.1.1-SNAPSHOT

$ lein plugin install org.cloudhoist/pallet-lein 0.4.2-SNAPSHOT

$ lein new pallet quickstart

$ cd quickstart

$ lein pallet add-service aws aws-ec2 MY_AWS_ACCESS_KEY_ID MY_AWS_SECRET_KEY
... 
Could not locate node definition for MY_AWS_SECRET_KEY
```

We have the same problem on Ubuntu 10.04 and OS X 10.6.8.

Thanks,
-Stuart Sierra

**Comment by hugoduncan** [comment]
Did you get past this, or is it still an issue?

**Comment by fdb** [comment]
I have the same problem using Leiningen 1:

```
$ lein pallet add-service aws aws-ec2 MY_AWS_ACCESS_KEY_ID MY_AWS_SECRET_KEY
That's not a task. Use "lein help" to list all tasks.
```

The next step fails as well:

```
$ lein pallet providers
That's not a task. Use "lein help" to list all tasks.
```

**Comment by hugoduncan** [comment]
@fdb which version of lein? (`lein version`)? which version of the plugins?

Note the updated plugin versions in: http://palletops.com/doc/first-steps/

**Comment by fdb** [comment]
My Leiningen version:

```
$ lein version
Leiningen 1.6.2 on Java 1.6.0_33 Java HotSpot(TM) 64-Bit Server VM
```

I was following the docs you mentioned so the versions come from there:
- lein-newnew 0.3.4
- pallet/lein-template 0.2.3.

**Comment by hugoduncan** [comment]
@fdb this seems to be triggered by 1.6.2. As a workaround, you might use leiningen 1.7.0 or later.

**Comment by hugoduncan** [comment]
https://github.com/technomancy/leiningen/issues/656 strikes again.

Should be fixed now.  You may have delete pallet-lein-new-0.5.0.jar from ~/.lein/plugins and ~/.m2/repository/org/cloudhoist/pallet-lein/0.5.0. Please re-open if you still have problems.
