### ISSUE TITLE
Pexpect equivalent for Pallet

### ISSUE THREAD

**Issue by ludovicc** [pallet/pallet.github.com#18]
Hello,
This how to is interesting http://palletops.com/doc/how-tos/using-pallet-with-existing-servers/ , but my servers can be accessed only in two steps: first you login by ssh with your private key, but if you want to do anything interesting (install solftare, change configuration files, stop/start servers), you need to run sudo with a privileged user and only then you can perform those more sensitive commands. Unless I can convince the sysadmins to grant me direct access to the servers - which they won't do for security reasons - I have to live with this restriction.
So far, I have make my deployment scripts in Python and I use python-pexpect to automatically provide the sudo password when the server requests it. How could I do something like that with Pallet?

Thanks,
Ludovic

**Comment by hugoduncan** [comment]
If I understand correctly, this matches how pallet works. Pallet uses an "admin user" to ssh to the servers - by default it uses your username and id_rsa key. All scripts are then run using sudo. The automated-admin-user crate is usually used in the bootstrap phase to set up the user account and grant passwordless sudo access. However, you can specify a sudo password in the admin user map. See http://palletops.com/doc/reference/node-push/ for specifying the admin user in `~/pallet/config.clj`. The map takes the same keys as specified in pallet.utils/make-user.

Is this what you were looking for?

**Comment by hugoduncan** [comment]
I assume the above was sufficient. If not, please reopen.
