### ISSUE TITLE
pallet doesn't show up in lein tasks

### ISSUE THREAD

**Issue by greenmang0** [pallet/pallet.github.com#20]
`$ lein plugin install lein-newnew 0.2.6` works fine.

Then

```
$ lein new pallet quickstart
```

Gives an error **Could not find template pallet on the classpath.**

Using `lein 1.7.1`

**Comment by hugoduncan** [comment]
Fixed in pallet/lein-template 0.2.2. This was caused by https://github.com/technomancy/leiningen/issues/656
