### ISSUE TITLE
All links from crates doc page are broken.

### ISSUE THREAD

**Issue by vapapav** [pallet/pallet.github.com#46]
http://palletops.com/pallet/doc/crates/

I had the urge to try and fix this myself, but the how-to for doing that is missing.

**Comment by tbatchelli** [comment]
Thanks for letting us know. We are updating the site this week, and a fix for the crate links will be part of this update.

Looks like we could use a how-to-fix-the-site :)

—

Antoni Batchelli,
- twitter: @tbatchelli , @disclojure
  --- email: tbatchelli@gmail.com
  ----- web: tbatchelli.org , disclojure.org
  ----- gpg: public key
