### ISSUE TITLE
Following the example to instantiate first host on rackspace cloud fails

### ISSUE THREAD

**Issue by eigenhombre** [pallet/pallet.github.com#8]
Set up project.clj as advised after 'lein new':

$  cat project.clj
(defproject quickstart "1.0.0-SNAPSHOT"
  :dependencies [[org.cloudhoist/pallet "0.6.6"]
                 [org.cloudhoist/pallet-crates-standalone "0.5.0"]
                 [org.slf4j/slf4j-api "1.6.1"]
                 [ch.qos.logback/logback-core "1.0.0"]
                 [ch.qos.logback/logback-classic "1.0.0"]
                 [org.jclouds/jclouds-all "1.0.0"]
                 [org.jclouds.driver/jclouds-jsch "1.0.0"]
                 [org.jclouds.driver/jclouds-slf4j "1.0.0"]]
  :repositories {"sonatype"
                 "http://oss.sonatype.org/content/repositories/releases"})

Set up .pallet config:
(defpallet
  :services
  {:rs  {:provider "cloudservers-us" :identity blahblahblah :credentials foofoobar}})

ran lein deps

Then,
$ lein repl
user=> (require 'pallet.core 'pallet.compute 'pallet.configure)
nil
user=> (pallet.core/converge (pallet.core/group-spec "mygroup" :count 1) :compute (pallet.configure/compute-service :gogrid))
java.lang.ClassCastException: java.lang.Boolean cannot be cast to clojure.lang.Associative (NO_SOURCE_FILE:0)
user=> ^D

Any ideas?  Thanks!

**Comment by tbatchelli** [comment]
hi there,

Not sure if this is the error, but you are creating a service named :rs but then using :gogrid for your converge call. 

Also, note that the first steps page has been updated with a different group spec: http://palletops.com/doc/first-steps/

**Comment by eigenhombre** [comment]
This was the issue, I think.  Thanks!
